<?php
$config = $block->getConfig();
?>
<script>
(function(w) {
    var WAIT_AFTER_ONLOAD_MILLISECONDS = 5000;

    if (!w) {
        return;
    }

    BOOMR = w.BOOMR || {};
    BOOMR.plugins = BOOMR.plugins || {};

    BOOMR.plugins.WaitAfterOnload = {
        complete: false,

        init: function() {
            BOOMR.subscribe("page_ready", function() {
                setTimeout(function() {
                    this.complete = true;
                    BOOMR.sendBeacon();
                }.bind(this), WAIT_AFTER_ONLOAD_MILLISECONDS);
            }, {}, this);
        },

        is_complete: function() {
            return this.complete;
        }
    };

    w.basicRumBoomerangConfig = {
        beacon_url: "<?= $block->escapeJs($config['beacon_endpoint']) ?>",
        instrument_xhr: true,
        Continuity: {
            enabled: true
        },
        ResourceTiming: {
            "enabled": true,
            "splitAtPath": true
        },
        secure_cookie: true,
        same_site_cookie: "Strict"

    }
})(window);
(function(d, s) {
  var js = d.createElement(s),
      sc = d.getElementsByTagName(s)[0];

  js.src="<?= $block->escapeJs($block->getViewFileUrl('BasicRum_Analytics::js/boomerang-1.815.60.cutting-edge.min.js')) ?>";
  sc.parentNode.insertBefore(js, sc);
}(document, "script"));
</script>
